// <auto-generated />
using System;
using Backend.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(DeportivoContext))]
    [Migration("20260219223449_SumeEdadYNivel")]
    partial class SumeEdadYNivel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Service.Models.Actividad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Beneficios")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EdadRecomendada")
                        .HasColumnType("longtext");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nivel")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProfesorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfesorId");

                    b.ToTable("Actividades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Clase de yoga para mejorar la flexibilidad y el bienestar general.",
                            EdadRecomendada = "Adultos",
                            Imagen = "portada1.jpg",
                            IsDeleted = false,
                            Nivel = "Principiante",
                            Nombre = "Yoga",
                            ProfesorId = 1
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Clase de pilates para fortalecer el core y mejorar la postura.",
                            EdadRecomendada = "Adultos",
                            Imagen = "portada2.jpg",
                            IsDeleted = false,
                            Nivel = "Principiante",
                            Nombre = "Pilates",
                            ProfesorId = 2
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Clase de zumba para quemar calorías y divertirse bailando.",
                            EdadRecomendada = "Adultos",
                            Imagen = "portada3.jpg",
                            IsDeleted = false,
                            Nivel = "Principiante",
                            Nombre = "Zumba",
                            ProfesorId = 3
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Clase de spinning para mejorar la resistencia cardiovascular.",
                            EdadRecomendada = "Adultos",
                            Imagen = "portada4.jpg",
                            IsDeleted = false,
                            Nivel = "Principiante",
                            Nombre = "Spinning",
                            ProfesorId = 4
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Clase de CrossFit para un entrenamiento intenso y variado.",
                            EdadRecomendada = "Adultos",
                            Imagen = "portada5.jpg",
                            IsDeleted = false,
                            Nivel = "Principiante",
                            Nombre = "CrossFit",
                            ProfesorId = 5
                        });
                });

            modelBuilder.Entity("Service.Models.Asistencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClaseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Presente")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("SocioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClaseId");

                    b.HasIndex("SocioId");

                    b.ToTable("Asistencias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaseId = 1,
                            Fecha = new DateTime(2026, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Presente = true,
                            SocioId = 1
                        },
                        new
                        {
                            Id = 2,
                            ClaseId = 1,
                            Fecha = new DateTime(2026, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Presente = false,
                            SocioId = 2
                        },
                        new
                        {
                            Id = 3,
                            ClaseId = 2,
                            Fecha = new DateTime(2024, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Presente = true,
                            SocioId = 1
                        },
                        new
                        {
                            Id = 4,
                            ClaseId = 2,
                            Fecha = new DateTime(2026, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Presente = true,
                            SocioId = 3
                        },
                        new
                        {
                            Id = 5,
                            ClaseId = 3,
                            Fecha = new DateTime(2026, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Presente = false,
                            SocioId = 2
                        });
                });

            modelBuilder.Entity("Service.Models.Clase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ActividadId")
                        .HasColumnType("int");

                    b.Property<int>("CupoMaximo")
                        .HasColumnType("int");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("ActividadId");

                    b.ToTable("Clases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activa = true,
                            ActividadId = 1,
                            CupoMaximo = 20,
                            DiaSemana = 1,
                            HoraFin = new TimeSpan(0, 19, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 18, 0, 0, 0),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            Activa = true,
                            ActividadId = 2,
                            CupoMaximo = 15,
                            DiaSemana = 3,
                            HoraFin = new TimeSpan(0, 20, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 19, 0, 0, 0),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            Activa = true,
                            ActividadId = 3,
                            CupoMaximo = 25,
                            DiaSemana = 5,
                            HoraFin = new TimeSpan(0, 18, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 17, 0, 0, 0),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            Activa = true,
                            ActividadId = 4,
                            CupoMaximo = 20,
                            DiaSemana = 2,
                            HoraFin = new TimeSpan(0, 19, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 18, 0, 0, 0),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            Activa = true,
                            ActividadId = 5,
                            CupoMaximo = 15,
                            DiaSemana = 4,
                            HoraFin = new TimeSpan(0, 20, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 19, 0, 0, 0),
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("Service.Models.Localidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Localidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Nombre = "San justo"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Nombre = "Videla"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Nombre = "Gobernador Crespo"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Nombre = "San Martín Norte"
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            Nombre = "Ramayón"
                        });
                });

            modelBuilder.Entity("Service.Models.Profesor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Profesores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            IsDeleted = false,
                            Nombre = "Juan Perez"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            IsDeleted = false,
                            Nombre = "Carlos Gomez"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            IsDeleted = false,
                            Nombre = "Pablo Garcia"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            IsDeleted = false,
                            Nombre = "Maria Lopez"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            IsDeleted = false,
                            Nombre = "Camila Fernandez"
                        });
                });

            modelBuilder.Entity("Service.Models.Socio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Domicilio")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("LocalidadId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("LocalidadId");

                    b.ToTable("Socios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Dni = "",
                            Domicilio = "",
                            FechaNacimiento = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LocalidadId = 1,
                            Nombre = "Sofia Martinez",
                            Telefono = ""
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Dni = "",
                            Domicilio = "",
                            FechaNacimiento = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LocalidadId = 2,
                            Nombre = "Luca Rodriguez",
                            Telefono = ""
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Dni = "",
                            Domicilio = "",
                            FechaNacimiento = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LocalidadId = 3,
                            Nombre = "Valentina Gomez",
                            Telefono = ""
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Dni = "",
                            Domicilio = "",
                            FechaNacimiento = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LocalidadId = 4,
                            Nombre = "Mateo Fernandez",
                            Telefono = ""
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Dni = "",
                            Domicilio = "",
                            FechaNacimiento = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LocalidadId = 5,
                            Nombre = "Camila Sanchez",
                            Telefono = ""
                        });
                });

            modelBuilder.Entity("Service.Models.SocioActividad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActividadId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("SocioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActividadId");

                    b.HasIndex("SocioId");

                    b.ToTable("SocioActividades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActividadId = 1,
                            IsDeleted = false,
                            SocioId = 1
                        },
                        new
                        {
                            Id = 2,
                            ActividadId = 2,
                            IsDeleted = false,
                            SocioId = 2
                        },
                        new
                        {
                            Id = 3,
                            ActividadId = 3,
                            IsDeleted = false,
                            SocioId = 3
                        },
                        new
                        {
                            Id = 4,
                            ActividadId = 4,
                            IsDeleted = false,
                            SocioId = 4
                        },
                        new
                        {
                            Id = 5,
                            ActividadId = 5,
                            IsDeleted = false,
                            SocioId = 5
                        });
                });

            modelBuilder.Entity("Service.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Domicilio")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("FechaRegistracion")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TipoRol")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Dni = "10000001",
                            Domicilio = "Calle 1",
                            Email = "juan1@mail.com",
                            FechaRegistracion = new DateTimeOffset(new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Nombre = "Juan Pérez",
                            Observacion = "",
                            Password = "pass1",
                            Telefono = "1111111",
                            TipoRol = 0
                        },
                        new
                        {
                            Id = 2,
                            Dni = "10000002",
                            Domicilio = "Calle 2",
                            Email = "ana2@mail.com",
                            FechaRegistracion = new DateTimeOffset(new DateTime(2023, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Nombre = "Ana Gómez",
                            Observacion = "",
                            Password = "pass2",
                            Telefono = "2222222",
                            TipoRol = 1
                        },
                        new
                        {
                            Id = 3,
                            Dni = "10000003",
                            Domicilio = "Calle 3",
                            Email = "luis3@mail.com",
                            FechaRegistracion = new DateTimeOffset(new DateTime(2023, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Nombre = "Luis Torres",
                            Observacion = "",
                            Password = "pass3",
                            Telefono = "3333333",
                            TipoRol = 0
                        },
                        new
                        {
                            Id = 4,
                            Dni = "10000004",
                            Domicilio = "Calle 4",
                            Email = "maria4@mail.com",
                            FechaRegistracion = new DateTimeOffset(new DateTime(2023, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Nombre = "María López",
                            Observacion = "",
                            Password = "pass4",
                            Telefono = "4444444",
                            TipoRol = 1
                        },
                        new
                        {
                            Id = 5,
                            Dni = "10000005",
                            Domicilio = "Calle 5",
                            Email = "pedro5@mail.com",
                            FechaRegistracion = new DateTimeOffset(new DateTime(2023, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Nombre = "Pedro Ruiz",
                            Observacion = "",
                            Password = "pass5",
                            Telefono = "5555555",
                            TipoRol = 1
                        });
                });

            modelBuilder.Entity("Service.Models.Actividad", b =>
                {
                    b.HasOne("Service.Models.Profesor", "Profesor")
                        .WithMany()
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("Service.Models.Asistencia", b =>
                {
                    b.HasOne("Service.Models.Clase", "Clase")
                        .WithMany()
                        .HasForeignKey("ClaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Service.Models.Socio", "Socio")
                        .WithMany()
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clase");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("Service.Models.Clase", b =>
                {
                    b.HasOne("Service.Models.Actividad", "Actividad")
                        .WithMany()
                        .HasForeignKey("ActividadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actividad");
                });

            modelBuilder.Entity("Service.Models.Socio", b =>
                {
                    b.HasOne("Service.Models.Localidad", "Localidad")
                        .WithMany()
                        .HasForeignKey("LocalidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Localidad");
                });

            modelBuilder.Entity("Service.Models.SocioActividad", b =>
                {
                    b.HasOne("Service.Models.Actividad", "Actividad")
                        .WithMany()
                        .HasForeignKey("ActividadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Service.Models.Socio", "Socio")
                        .WithMany("SocioActividades")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actividad");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("Service.Models.Socio", b =>
                {
                    b.Navigation("SocioActividades");
                });
#pragma warning restore 612, 618
        }
    }
}
